# Generated by Django 4.0.2 on 2022-02-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0005_alter_file_owner_alter_image_owner_alter_text_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
